version: "3.3"

services:
  server2:
    container_name: server2
    build:
      context: .
      dockerfile: ./server2/Dockerfile
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "9453:3001"
    volumes:
      - "./server2/nginx.conf:/etc/nginx/sites-available/default.conf"

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - "./mysql/schema:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_DATABASE=ifb102
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    expose:
      - "3306"